### ISSUE TITLE
Implement Search + Product Page + Categories Page

### ISSUE THREAD

**Issue by ArfatSalman** [pesto-students/little-tags-FE-nishantbisen09#17]
# Instructions

**As per your mocks**, start implementing the product search feature, categories page, and the single product page itself. More info is provided below.

## Where will I get data to render?

If the _fakestoreapi_ is not helpful, feel free to mock the data by creating a JSON file with any relevant data yourself. The only thing you need to be careful is that you should fix the shape of the data and assume that this data was coming from the server itself. This way, once you have the server ready, you can just change the source. I agree that there will be front-end changes when the app is paired with the server, but hopefully they should be minimal if the shape is consistent.

**Also, remember that _any_ API can and will fail. So take the error cases into account as well.**

# Requirements

## Product Search Feature

When the user starts typing a product, you should show an autocomplete results box (or page if that's what your mock has) with the results. User should be able to `tab` through the results. Other natural keyboard buttons should also work.

## Categories Page

The product display should have **price**, **product name** and **rating** at the very least. There should also be a "Add to cart" button (this doesn't have to work). The user should be able to filter the product set with a few things of your choosing. Also, the user should be able to sort the set based on some criteria (such as price, rating etc.)

## Single Product Page

The page should show the price, description (if any), rating, images, quantity, add to cart, add to wishlist etc.

**Feel free to add more things on these pages if they are present in your mocks.**

# Checklist of requirement

- [x] Autocomplete Product Search Feature
  - [x] Render correct outputs
  - [x] Has Autocomplete
  - [x] Tab Accessible
  - [x] Mobile Responsive
- [x] Categories Page
  - [x] Mobile Responsive
  - [x] Left side bar with filters
  - [x] Sort the product set (for e.g. on the basis of price)
  - [x] Tab Accessible
- [x] Product Page
  - [x] Mobile Responsive
  - [x] All relevant details are visible
  - [x] Tab Accessible
- [x] Routes should change upon going to different screens
- [x] At least 2 End to End test (see resources)
- [x] i18n should continue to work
- [x] Should not have [regression bugs](https://en.wikipedia.org/wiki/Software_regression)

# Resources

- [List of Autocomplete libs](https://blog.bitsrc.io/top-react-autocomplete-libraries-in-2020-1b300476eb0e)
- [Accessibility in React](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_accessibility)
- Read [this](https://kentcdodds.com/blog/unit-vs-integration-vs-e2e-tests) before proceeding with E2E testing. Use [puppeteer.js](https://developers.google.com/web/tools/puppeteer) or [Cypress](https://www.cypress.io/) (make a choice and comment it below) to make at least two E2E tests for your application. Try to do this at the end of the making the search, product, and product feature. Here's a tutorial for using [Cypress with React](https://css-tricks.com/using-cypress-to-write-tests-for-a-react-application/). Here are two articles for puppeteer: [1](https://blog.scottlogic.com/2020/01/22/react-app-puppeteer.html) and [2](https://blog.scottlogic.com/2020/01/22/react-app-puppeteer.html)

# Need help?

Comment on this thread if there is any confusion with the requirements. Try to follow your mocks. Don't drastically change things until needed. Minor modifications are allowed.

**Comment by nishantbisen09** [comment]
I have gone through the instructions and observed that multiple external resources are required to complete the listed features.
First things first
#### Where will I get data to render?
I have few suggestions based on the latest home page presented by us on 01-03-2021 that include
- We should generate as much fake data as possible because we already have the resources (at least for the home page because we do have **top-categories** & **featured-products** over there) because
    - That would gradually increase the development speed
    - Reduce searching time
- Also Tejas had this _**women-centric design**_ idea in his mind so based on that I suggest we should use [Commerce.js](https://commercejs.com/docs/) as our backend, for now, also @ArfatSalman can you please share your views after going through the docs of this commerce API. (Fake data generation may still be needed)

**Comment by ArfatSalman** [comment]
> also @ArfatSalman can you please share your views after going through the docs of this commerce API. 

I won't be able to make that decision for you guys. Moreover, skimming the docs is not going to be fruitful as I have **no** prior experience with Commerce.js. I don't have the time to read it thoroughly currently unfortunately.  😞 

So if you have some experience, you can go with it. Otherwise, I'd generally not recommend very very heavy frameworks such as one mentioned above. 

> We should generate as much fake data

Yes. Make json / js / yaml file with fake data (make a folder so that you have all the data in one place), host iamges on imgur / S3. The current goal is to showcase an "ideal" layout of an e-commerce application.  😊

**Comment by nishantbisen09** [comment]
> So if you have some experience, you can go with it. Otherwise, I'd generally not recommend very very heavy frameworks such as one mentioned above.

I was exploring things to get fake data more easily, but then I don't really have used it before, so yes we should skip it.

> Yes. Make json / js / yaml file with fake data (make a folder so that you have all the data in one place), host iamges on imgur / S3. The current goal is to showcase an "ideal" layout of an e-commerce application. 😊

Yes, I think this is the best possible approach for now.

Thanks @ArfatSalman

**Comment by CodingCreate101** [comment]
Going to use Cypress for E2E testing :)

**Comment by nishantbisen09** [comment]
## Autocomplete Product Search Feature (Desktop)
![autoComplete_Desk](https://user-images.githubusercontent.com/37059929/110699526-f5d0f100-8214-11eb-8ac2-a87871469662.gif)

## Autocomplete Product Search Feature (Mobile)
![autoComplete_Mob](https://user-images.githubusercontent.com/37059929/110699593-08e3c100-8215-11eb-936b-a229d4abef64.gif)

## Categories Page (Desktop)
![categories_desktop](https://user-images.githubusercontent.com/37059929/110700154-a3440480-8215-11eb-9e1e-483066a5eca3.gif)

## Categories Page (Mobile)
![categories_mobile](https://user-images.githubusercontent.com/37059929/110700197-b060f380-8215-11eb-8be1-0e86bfe27e2c.gif)

## Product Page (Desktop)
![prod_desk](https://user-images.githubusercontent.com/37059929/110701140-ce7b2380-8216-11eb-9022-2caba6dab786.gif)

## Product Page (Mobile
![prod_mob](https://user-images.githubusercontent.com/37059929/110701180-d935b880-8216-11eb-8321-2ab8e2c5087f.gif)

**Comment by CodingCreate101** [comment]
All points in this issue are covered. Closing.
